FROM python:3.11-slim-bookworm
ENV PYTHONUNBUFFERED=1 PYTHONDONTWRITEBYTECODE=1
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt && useradd --uid 10001 --create-home everypost && mkdir /data && chown everypost /data
COPY *.py *.html *.pem ./
USER everypost
CMD ["python", "-u", "app.py"]
